name: DFix
main: DFix\Main
version: 1.0.7
api: [1.0.0]
load: STARTUP
author: glorydark
commands:
 fix:
  description: DFix
  usage: /fix
permissions:
 DFix.*:
  default: true
  description: 根权限
  children:
  DFix.command:
   default: true
   description: 所有指令权限
   children:
    DFix.command.fix:
     default: true
     description: 修复命令